### ISSUE TITLE
偶发性报错 await handleCommand$1(commands, this.opts?.options);

### ISSUE THREAD

**Issue by M69W** [xianweics/filemanager-plugin#19]
同一份代码，服务器构建，出现了偶发性报错
本地构建正常

```
node -v
v12.18.2
npm -v
6.14.5
```
package.json
```
"devDependencies": {
    "filemanager-plugin": "^2.8.2",
    "webpack": "^5.91.0",
    "webpack-cli": "^5.1.4"
  }
```

webpack.config.js
```
const path = require("path");
const FileManagerPlugin = require("filemanager-plugin").WebpackFilemanager;
 
module.exports = {
  mode: "development",
  entry: "./src/index.js", // 入口文件路径
  output: {
    filename: "test.js", // 输出文件名
    path: path.resolve(__dirname, "dist"), // 输出目录路径
  },
  module: {
    rules: [
      // 这里可以添加各种loader规则，如处理CSS、图片等文件类型
    ],
  },
  // 其他配置项...
  plugins: [
    new FileManagerPlugin({
      events: {
        start: {
            del: {
                items: ["./dist"]
            },
        },
        end: {
            unzip: {
                items: [
                  {
                    source: "./files/test/xx.zip", 
                    destination: "./files/test/xx/",
                    type: "zip"
                  }
                ]
              },
              copy: {
                items: [
                  {
                    source: "./files/test/xx/",
                    destination: "./dist/"
                  }
                ]
              },
              del: {
                items: [
                  "./dist/test.js",
                  "./files/test/xx/"
                ]
              },
        }
      }
    })
  ]
};
```
异常
```
> webpack

[webpack-cli] Failed to load 'xxx/webpack.config.js' config
[webpack-cli] xxx/workspace/node_modules/filemanager-plugin/lib/index.js:177
      await handleCommand$1(commands, this.opts?.options);
                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (xxx/webpack.config.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! H5@0.0.1 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the H5@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by xianweics** [comment]
这个是由于node.js12 不支持?.语法解析。需要nodejs14才支持。

**Comment by M69W** [comment]
感谢回复。
现已改为别的发布流程，不再依赖 项目node 版本
再次感谢，这个插件确实不错。
