### ISSUE TITLE
TypeError: Cannot read property 'parallel' of undefined

### ISSUE THREAD

**Issue by nikolay-borzov** [xianweics/filemanager-plugin#2]
An exception is thrown when trying to move files
```js
new FileManagerPlugin({
  events: {
    end: {
      move: {
        items: [
          { source: './build/svg', destination: './dist/svg' }
        ]
      }
    }
  }
})
```

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parallel' of undefined

<details>
<summary>Exception stack</summary>

```
    at _callee$ (\node_modules\filemanager-plugin\lib\index.js:180:38)
    at tryCatch (\node_modules\filemanager-plugin\lib\index-bc442c85.js:87:17)
    at Generator.invoke [as _invoke] (\node_modules\filemanager-plugin\lib\index-bc442c85.js:304:22)
    at Generator.next (\node_modules\filemanager-plugin\lib\index-bc442c85.js:140:21)
    at asyncGeneratorStep (\node_modules\filemanager-plugin\lib\index-bc442c85.js:752:24)
    at _next (\node_modules\filemanager-plugin\lib\index-bc442c85.js:774:9)
    at \node_modules\filemanager-plugin\lib\index-bc442c85.js:781:7
    at new Promise (<anonymous>)
    at \node_modules\filemanager-plugin\lib\index-bc442c85.js:770:12
    at _handleCommand (\node_modules\filemanager-plugin\lib\index.js:259:25)
    at handleCommand (\node_modules\filemanager-plugin\lib\index.js:143:25)
    at _callee$ (\node_modules\filemanager-plugin\lib\index.js:318:26)
    at tryCatch (\node_modules\filemanager-plugin\lib\index-bc442c85.js:87:17)
    at Generator.invoke [as _invoke] (\node_modules\filemanager-plugin\lib\index-bc442c85.js:304:22)
    at Generator.next (\node_modules\filemanager-plugin\lib\index-bc442c85.js:140:21)
    at asyncGeneratorStep (\node_modules\filemanager-plugin\lib\index-bc442c85.js:752:24)
    at _next (\node_modules\filemanager-plugin\lib\index-bc442c85.js:774:9)
    at \node_modules\filemanager-plugin\lib\index-bc442c85.js:781:7
    at new Promise (<anonymous>)
    at \node_modules\filemanager-plugin\lib\index-bc442c85.js:770:12
    at \node_modules\filemanager-plugin\lib\index.js:332:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at AsyncSeriesHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)
    at \node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (\node_modules\webpack\lib\Compiler.js:499:39)
    at \node_modules\webpack\lib\Compiler.js:298:10
    at \node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)
    at \node_modules\webpack\lib\Compiler.js:482:27
    at \node_modules\neo-async\async.js:2818:7
    at done (\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at \node_modules\webpack\lib\Compiler.js:464:33
    at \node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:61:14
    at \node_modules\graceful-fs\graceful-fs.js:43:10
```

</details>

I guess it is somehow related to this change https://github.com/xianweics/filemanager-plugin/commit/b1620b62476c494279b8ec09bb070888038e867d#diff-001bb55757ea1677379c1009eb099108R28

**Comment by xianweics** [comment]
@nikolay-borzov. Thank you for your feedback. It was fixed at version 2.5.1.  Also, you add `{}` options to fix it.
```javascript
new FileManagerPlugin({
  events: {
    end: {
      move: {
        items: [
          { source: './build/svg', destination: './dist/svg' }
        ]
      }
    }
  },
  options: {}
})
```
